### ISSUE TITLE
Glitches in GUI applications

### ISSUE THREAD

**Issue by arvydasg** [microsoft/wslg#1148]
### Windows build number:

10.0.22631.0

### Your Distribution version:

22.04

### Your WSL versions:

WSL version: 2.0.9.0
Kernel version: 5.15.133.1-1
WSLg version: 1.0.59
MSRDC version: 1.2.4677
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22631.2715

### Steps to reproduce:

1. activate wsl on windows
2. install ubuntu distro either from MS store or from terminal by wsl --install or wsl --install ubuntu
3. update ubuntu distro sudo apt update && upgrade
4. install emacs, vlc or nautilus
5. launch one of those, I get this behavior as described in the screenshots

### WSL logs:

[stderr.log](https://github.com/microsoft/wslg/files/13463056/stderr.log)
[weston.log](https://github.com/microsoft/wslg/files/13463057/weston.log)
[pulseaudio.log](https://github.com/microsoft/wslg/files/13463058/pulseaudio.log)

### Expected behavior:

WSL should run gui applications without the glitches.

### Actual behavior:

I had wsl working just fine until yesterday! Everything I am about to eplain about was working fine yesterday.

Yesterday I have installed another ubuntu version on my wsl, alongside fully working wsl version. So I had 2x ubuntu versions + the default docker wsl's.

This strange gui glitch started to happen when I launch emacs gui application. If I launch it in the terminal - all is good.
emacs gui with glitches:
![emacs](https://github.com/microsoft/wslg/assets/78803192/42be3651-5a42-427e-9b94-0ef304cf16e6)

emacs over terminal:
![emacs_terminal](https://github.com/microsoft/wslg/assets/78803192/34ede521-b35f-44d8-abda-8ca81ee25a26)

When I move the emacs gui screen - the glitch dissapears. When I stop moving it - it reappears.

I thought okay I can not work like this, I need to start fresh. I then unregistered both ubuntu distros and went to "add remove programs" to uninstall those ubuntu versions.

I installed ubuntu from terminal by wls --install ubuntu or wsl --install or from ms store, restarts...- same problem.

I then disabled WSL feature.  Restarts... installed wsl again, did wsl --set-default-version 2 - same problem.

I then tried to install another GUI application - nautilus and VLC - same probelm with those:
![nautilus](https://github.com/microsoft/wslg/assets/78803192/a8308d16-5a93-4f1b-aa9a-50ecf122dcb0)
![vlc](https://github.com/microsoft/wslg/assets/78803192/41e8d31c-7cce-4ea7-8cc4-90deea384ba3)

I then thought thanks god its not related with emacs, its a gui bug in general with all linux applications over wsl. Nothing similar happens on my windows apps.

That helped me to narrow the problem down. Insead of googling "emacs gui glitches in wsl", I started to google for "wsl gui glitches".

I then found out about wslg and that it is responsible for launching gui applications over wsl.

I then installed mobaxterm since I guess it does not use wslg, but uses xserver. I then tried to launch emacs with it:

x server off - emacs launched in terminal mode:

![xserver_off](https://github.com/microsoft/wslg/assets/78803192/fac3757b-ed00-41fc-9bac-55523d1caa3c)

x server  on - emacs launched in gui mode:

![xserver_on](https://github.com/microsoft/wslg/assets/78803192/fa963fbc-e94f-4625-b048-60b4b0e6ccb6)

Finally emacs has no glitches!!!

I dont really want to reset my windows to make wsl not glitch anymore, can you help me find a way what to update/remove/reinstall to make these glitches go away?

Thank you!

p.s. this is everything I have installed right now that I know regarding wsl, hope that helps:

![versions](https://github.com/microsoft/wslg/assets/78803192/8deddca7-c992-4f3b-8f8e-e0608794436a)

**Comment by arvydasg** [comment]
Addition with some **videos**:

Sometimes it works:

https://github.com/microsoft/wslg/assets/78803192/98f11bb5-a0d6-4760-8f49-4840dca11719

Sometimes it does not work:


https://github.com/microsoft/wslg/assets/78803192/729bae6c-db4b-4771-8698-3743e79ce57a

**Comment by vielhuber** [comment]
I have exactly the same problem.

This is gedit:

![image](https://github.com/microsoft/wslg/assets/3183737/eb2aaf26-857a-4fbb-89d5-78a4c84451b3)

**Comment by vielhuber** [comment]
Downgrading to 2.0.4 seems to be an option:

https://github.com/microsoft/wslg/issues/1130

**Comment by arvydasg** [comment]
> Downgrading to 2.0.4 seems to be an option:
> 
> #1130

Amazing @vielhuber, that sounds promsing. good detective work!

How would one go about with downgrading wsl? Did you succeed? Is the glitching gone for you?

**Comment by vielhuber** [comment]
I tried:

- Updated nvidia drivers (via "GeForce Experience")
- ```sudo apt update```
- ```sudo apt upgrade```
- ```wsl --shutdown``` via PowerShell (Admin)

Then it worked until a restart.

Identified that after boot I manually once always need to run ```wsl --shutdown```, then it works.

I can't downgrade at the moment and am waiting for an official fix.

**Comment by arvydasg** [comment]
Will wait for an official fix then also.

Untl then I will run my wsl gui applications over https://mobaxterm.mobatek.net/ . Give it a try, it's cool!

**Comment by salarmehr** [comment]
The exact issue here.  @arvydasg could you try the downgrading suggestion?

**Comment by arvydasg** [comment]
Surprisingly the issue does not repeat anymore. Will try it if it happens again.

**Comment by nikosandreou** [comment]
Same issue here. Windows 11 with following WSL issue

`WSL version: 2.0.9.0
Kernel version: 5.15.133.1-1
WSLg version: 1.0.59
MSRDC version: 1.2.4677
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22631.2715
PS C:\Users\nandreou>`

I did an update in Intel Drivers update and Windows Update simultaneously so not sure what broke it. However, I tried the following:

-In .wslgconfig I added 

`[system-distro-env]
;disable GPU in system-distro
LIBGL_ALWAYS_SOFTWARE=1`

-Restarted wsl. Worked.
-Restarted laptop, the fix still works.

Maybe other people try this and post their feedback.

**Comment by MarcosRguez** [comment]
¡Worked for me!

**Comment by bluejoyq** [comment]
> Same issue here. Windows 11 with following WSL issue
> 
> > WSL version: 2.0.9.0
> > Kernel version: 5.15.133.1-1
> > WSLg version: 1.0.59
> > MSRDC version: 1.2.4677
> > Direct3D version: 1.611.1-81528511
> > DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
> > Windows version: 10.0.22631.2715
> 
> I did an update in Intel Drivers update and Windows Update simultaneously so not sure what broke it. However, I tried the following:
> 
> -In .wslgconfig I added
> 
> > [system-distro-env]
> > ;disable GPU in system-distro
> > LIBGL_ALWAYS_SOFTWARE=1
> 
> -Restarted wsl. Worked. -Restarted laptop, the fix still works.
> 
> Maybe other people try this and post their feedback.

Worked For Me! Thanks!

**Comment by Benargee** [comment]
I had a similar problem. I installed Kali in WSL then I installed x11-apps just for a simple test.   
When I launched xeyes and xcalc it was glitching out. All I had to do to fix it was restart Windows 11.

```
PS C:\Users\benargee>wsl -v
WSL version: 2.0.9.0
Kernel version: 5.15.133.1-1
WSLg version: 1.0.59
MSRDC version: 1.2.4677
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22631.2715
```

**Comment by admin-elvistrujanovic** [comment]
> I had a similar problem. I installed Kali in WSL then I installed x11-apps just for a simple test.   
> When I launched xeyes and xcalc it was glitching out. All I had to do to fix it was restart Windows 11.
> 
> ```
> PS C:\Users\benargee>wsl -v
> WSL version: 2.0.9.0
> Kernel version: 5.15.133.1-1
> WSLg version: 1.0.59
> MSRDC version: 1.2.4677
> Direct3D version: 1.611.1-81528511
> DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
> Windows version: 10.0.22631.2715
> ```

Well that didn't helped me... Probably it's an bug in the code since I'm not the only person who have these issues so I hope that WSLg developers will look into this case and at least try to fix it from their side.

**Comment by palapapa** [comment]
FYI I had to put the .wslgconfig file in C:\ProgramData\Microsoft\WSL. The WSL folder didn't exist so I had to create it manually.

**Comment by BiruBear** [comment]
So I was having this problem as well, nothing above worked so, identifying the problem in wslg, I disabled it by adding in C:\Users\youruser\ .wslconfig
`[wsl2]`
`guiApplications=false`
as suggested in [https://github.com/microsoft/wslg/discussions/523](https://github.com/microsoft/wslg/discussions/523) and restarted.

Then I used MobaXterm as X server, exported its display destination in the $DISPLAY variable and all solved.

**Comment by analytic-garden** [comment]
Same problem. It is intermittent. I have updated NVIDIA and Intel drivers, but that had no effect. The problem still arises, seemingly at random.

**Comment by supra621** [comment]
I just ran into this as well on a fresh install of WSL2. `wsl --v` output:

```
WSL version: 2.0.9.0
Kernel version: 5.15.133.1-1
WSLg version: 1.0.59
MSRDC version: 1.2.4677
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22631.2715
```

Running on a Vega 56 GPU, and didn't experience it on the older version of WSL2 I had installed previously. Updating the AMD drivers didn't resolve it. Following the suggestion in the thread to add the `LIBGL_ALWAYS_SOFTWARE=1` to `.wslgconfig` seems to fix it for me.

What are the implications of setting the `LIBGL_ALWAYS_SOFTWARE` variable? Just want to make a note if it can (or should) be removed from the configuration if a fix is released.

**Comment by nikosandreou** [comment]
> I just ran into this as well on a fresh install of WSL2. `wsl --v` output:
> 
> ```
> WSL version: 2.0.9.0
> Kernel version: 5.15.133.1-1
> WSLg version: 1.0.59
> MSRDC version: 1.2.4677
> Direct3D version: 1.611.1-81528511
> DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
> Windows version: 10.0.22631.2715
> ```
> 
> Running on a Vega 56 GPU, and didn't experience it on the older version of WSL2 I had installed previously. Updating the AMD drivers didn't resolve it. Following the suggestion in the thread to add the `LIBGL_ALWAYS_SOFTWARE=1` to `.wslgconfig` seems to fix it for me.
> 
> What are the implications of setting the `LIBGL_ALWAYS_SOFTWARE` variable? Just want to make a note if it can (or should) be removed from the configuration if a fix is released.

Well, GPU acceleration in WSLg has been a bit questionable. You can read this:

https://github.com/microsoft/wslg/issues/469

However, there are apps that may expect the GPU acceleration to be on so in case something crashes, you may have to turn it on. From my side, since I do mostly development in WSLg, having it on or off, doesn't bother me. I had it on for a couple of apps that were 'nice-to-use/have', but since this bug, I turned it off. I may turn it on if they fix the bug, but leaving it off won't hurt my daily programming life in WSLg.

**Comment by dtramer** [comment]
Unlike seemingly everyone else here ... I don't have this issue when wsl starts up.  But if I shut wsl down and restart it only then do I start seeing the issue, until I reboot my computer.  I figure I must be doing something wrong when I shut it down and restart it.

**Comment by Benja1972** [comment]
Have same issue 

```
PS C:\Users\*****> wsl --version
WSL version: 2.0.9.0
Kernel version: 5.15.133.1-1
WSLg version: 1.0.59
MSRDC version: 1.2.4677
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22621.2715
```

**Comment by EmpereurWaza** [comment]
Same issue here with latest WSL
![image](https://github.com/microsoft/wslg/assets/21972359/8186ba69-031a-4351-9607-a57831543b18)

```
Version WSL : 2.0.14.0
Version du noyau : 5.15.133.1-1
Version WSLg : 1.0.59
Version MSRDC : 1.2.4677
Version direct3D : 1.611.1-81528511
Version de DXCore : 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Version de Windows : 10.0.19045.3758
```

**Comment by Spencillian** [comment]
Same issue running the Quartus installer
![image](https://github.com/microsoft/wslg/assets/48698410/de214a48-c0cb-4171-8463-fffbc2e87a30)
My versions for everything are the same as above, except for windows version which is slightly updated
```
WSL version: 2.0.14.0
Kernel version: 5.15.133.1-1
WSLg version: 1.0.59
MSRDC version: 1.2.4677
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22635.2850
```
I've noticed that if I drag and move the window around, it briefly returns the normal expected screen. Not sure how much that helps. If I can be of any other help please let me know.

**Comment by birdue** [comment]
[This reddit post](https://www.reddit.com/r/wsl2/comments/y7epv4/cant_get_wslg_to_work_in_windows_11_no_mntwslg/) solved it for me.

- In the Windows directory `C:\Users\<username>` (also accessible by pasting `%USERPROFILE%` in the address bar in Explorer), create a file named `.wslconfig`
- Open the file and paste the following:
  ```
  [wsl2]
  guiApplications = true
  ```
- Restart WSL.

I can now run GUI apps without any glitches. Not sure if the issue will reoccur, though

**Comment by vielhuber** [comment]
> [This reddit post](https://www.reddit.com/r/wsl2/comments/y7epv4/cant_get_wslg_to_work_in_windows_11_no_mntwslg/) solved it for me.
> 
> * In the Windows directory `C:\Users\<username>` (also accessible by pasting `%USERPROFILE%` in the address bar in Explorer), create a file named `.wslconfig`
> * Open the file and paste the following:
>   ```
>   [wsl2]
>   guiApplications = true
>   ```
> * Restart WSL.
> 
> I can now run GUI apps without any glitches. Not sure if the issue will reoccur, though

Didn't work for me after restarting the computer.

**Comment by 38leinaD** [comment]
Same issue for me. Worked at some previous WSL version but now is broken.
![image](https://github.com/microsoft/wslg/assets/413413/01c28129-8d5a-4f77-b495-df475e6b84cd)

```
WSL version: 2.0.14.0
Kernel version: 5.15.133.1-1
WSLg version: 1.0.59
MSRDC version: 1.2.4677
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.19045.3693
```

Nothing described above helped yet. Updated to latest nvidia driver. LIBGL_ALWAYS_SOFTWARE=1,... 

Any idea is appreciated as it makes it virtually unusable for most of my workflow.

**Comment by BiruBear** [comment]
> Same issue for me. Worked at some previous WSL version but now is broken. ![image](https://private-user-images.githubusercontent.com/413413/290990617-01c28129-8d5a-4f77-b495-df475e6b84cd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI3NzI0ODIsIm5iZiI6MTcwMjc3MjE4MiwicGF0aCI6Ii80MTM0MTMvMjkwOTkwNjE3LTAxYzI4MTI5LThkNWEtNGY3Ny1iNDk1LWRmNDc1ZTZiODRjZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxN1QwMDE2MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YmNmYmUxZTFkMGJhZmFmNjY1Njg5NGM4OWUwMDcyODEwMTYwMjRjNDM0NzYyOGZhNTI0NmQ5NDUwZTYwZGNjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.mL75gbGGgxG0lQoSLtokBmr7dIHnbVBaetmtVklO_EI)
> 
> ```
> WSL version: 2.0.14.0
> Kernel version: 5.15.133.1-1
> WSLg version: 1.0.59
> MSRDC version: 1.2.4677
> Direct3D version: 1.611.1-81528511
> DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
> Windows version: 10.0.19045.3693
> ```
> 
> Nothing described above helped yet. Updated to latest nvidia driver. LIBGL_ALWAYS_SOFTWARE=1,...
> 
> Any idea is appreciated as it makes it virtually unusable for most of my workflow.
> 
> Current .wslgconfig
> 
> ```
> [system-distro-env]
> WSLG_USE_MSTSC=false
> WESTON_RDP_WINDOW_SNAP_ARRANGE=true
> WESTON_RDPRAIL_SHELL_LOCAL_MOVE=true
> ;disable GPU in system-distro
> LIBGL_ALWAYS_SOFTWARE=1
> ```
> 
> Using the Debian distro in WSL. Graphics card is NVIDIA GeForce RTX 2060.

Have you tried to deactivate wslg completely, like I have suggested above?

**Comment by 38leinaD** [comment]
> > Same issue for me. Worked at some previous WSL version but now is broken. ![image](https://private-user-images.githubusercontent.com/413413/290990617-01c28129-8d5a-4f77-b495-df475e6b84cd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI3NzI0ODIsIm5iZiI6MTcwMjc3MjE4MiwicGF0aCI6Ii80MTM0MTMvMjkwOTkwNjE3LTAxYzI4MTI5LThkNWEtNGY3Ny1iNDk1LWRmNDc1ZTZiODRjZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxN1QwMDE2MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YmNmYmUxZTFkMGJhZmFmNjY1Njg5NGM4OWUwMDcyODEwMTYwMjRjNDM0NzYyOGZhNTI0NmQ5NDUwZTYwZGNjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.mL75gbGGgxG0lQoSLtokBmr7dIHnbVBaetmtVklO_EI)
> > ```
> > WSL version: 2.0.14.0
> > Kernel version: 5.15.133.1-1
> > WSLg version: 1.0.59
> > MSRDC version: 1.2.4677
> > Direct3D version: 1.611.1-81528511
> > DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
> > Windows version: 10.0.19045.3693
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Nothing described above helped yet. Updated to latest nvidia driver. LIBGL_ALWAYS_SOFTWARE=1,...
> > Any idea is appreciated as it makes it virtually unusable for most of my workflow.
> > Current .wslgconfig
> > ```
> > [system-distro-env]
> > WSLG_USE_MSTSC=false
> > WESTON_RDP_WINDOW_SNAP_ARRANGE=true
> > WESTON_RDPRAIL_SHELL_LOCAL_MOVE=true
> > ;disable GPU in system-distro
> > LIBGL_ALWAYS_SOFTWARE=1
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Using the Debian distro in WSL. Graphics card is NVIDIA GeForce RTX 2060.
> 
> Have you tried to deactivate wslg completely, like I have suggested above?

No. I am interested in getting wslg working. I assume that might work and that was the approach when wslg was not available, but this issue is specifically about wslg. Or will this bring any insight for the wslg issue you mean?

**Comment by 38leinaD** [comment]
> I guess this might work: End task of WSL from task manager and open Ecmas or whatever app you want to use from start menu (not through terminal)

i dont understand. how can i open a wsl app from the hosts start menu?

**Comment by nikosandreou** [comment]
@38leinaD 

Like this

![start_menu](https://github.com/microsoft/wslg/assets/152171018/14bafd0f-5a79-48d2-a783-a467f13f126d)

**Comment by BiruBear** [comment]
> > > Same issue for me. Worked at some previous WSL version but now is broken. ![image](https://private-user-images.githubusercontent.com/413413/290990617-01c28129-8d5a-4f77-b495-df475e6b84cd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI3NzI0ODIsIm5iZiI6MTcwMjc3MjE4MiwicGF0aCI6Ii80MTM0MTMvMjkwOTkwNjE3LTAxYzI4MTI5LThkNWEtNGY3Ny1iNDk1LWRmNDc1ZTZiODRjZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxN1QwMDE2MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YmNmYmUxZTFkMGJhZmFmNjY1Njg5NGM4OWUwMDcyODEwMTYwMjRjNDM0NzYyOGZhNTI0NmQ5NDUwZTYwZGNjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.mL75gbGGgxG0lQoSLtokBmr7dIHnbVBaetmtVklO_EI)
> > > ```
> > > WSL version: 2.0.14.0
> > > Kernel version: 5.15.133.1-1
> > > WSLg version: 1.0.59
> > > MSRDC version: 1.2.4677
> > > Direct3D version: 1.611.1-81528511
> > > DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
> > > Windows version: 10.0.19045.3693
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Nothing described above helped yet. Updated to latest nvidia driver. LIBGL_ALWAYS_SOFTWARE=1,...
> > > Any idea is appreciated as it makes it virtually unusable for most of my workflow.
> > > Current .wslgconfig
> > > ```
> > > [system-distro-env]
> > > WSLG_USE_MSTSC=false
> > > WESTON_RDP_WINDOW_SNAP_ARRANGE=true
> > > WESTON_RDPRAIL_SHELL_LOCAL_MOVE=true
> > > ;disable GPU in system-distro
> > > LIBGL_ALWAYS_SOFTWARE=1
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Using the Debian distro in WSL. Graphics card is NVIDIA GeForce RTX 2060.
> > 
> > 
> > Have you tried to deactivate wslg completely, like I have suggested above?
> 
> No. I am interested in getting wslg working. I assume that might work as that was the approach when wslg was not yet available. Or will this bring any insight for the wslg issue you mean?

Not many insights, it just proves that wslg is the source of this problem. You are correct, I always used WSL with a third-party X server. WSLg is convenient, but I can survive without it, I never checked the eventual advantages.

**Comment by x0wllaar** [comment]
I can add to this issue with my comment on #1025:

Can reproduce on Win11 with cool-retro-term

To reproduce (on Ubuntu 22.04):

```
sudo apt install cool-retro-term
cool-retro-term
```

![Screenshot 2023-12-19 195032](https://github.com/microsoft/wslg/assets/10964379/583b9053-aac2-4070-bd71-ad4e97b5057d)

A fully transparent window will appear, mouse events will go to the window below.

When running as `LIBGL_ALWAYS_SOFTWARE=1 cool-retro-term`, everything works as expected:
![Screenshot 2023-12-19 195248](https://github.com/microsoft/wslg/assets/10964379/66647af3-e6d7-43d7-b406-1c82a593204a)

This is fairly similar to this issue in CRT's repo: https://github.com/Swordfish90/cool-retro-term/issues/217, which turned out to be a driver issue, so this suggests that it's some incompatibility between QML and WSLg.

Running `QSG_INFO=1 cool-retro-term` shows the empty window and prints the following in the terminal:

```
qt.scenegraph.general: threaded render loop
qt.scenegraph.general: Using sg animation driver
qt.scenegraph.general: Animation Driver: using vsync: 16.68 ms
Both point size and pixel size set. Using pixel size.
qt.scenegraph.general: Using sg animation driver
qt.scenegraph.general: Animation Driver: using vsync: 16.68 ms
qt.scenegraph.general: opengl texture atlas dimensions: 1024x1024
qt.scenegraph.general: R/G/B/A Buffers:   8 8 8 8
qt.scenegraph.general: Depth Buffer:      24
qt.scenegraph.general: Stencil Buffer:    8
qt.scenegraph.general: Samples:           -1
qt.scenegraph.general: GL_VENDOR:         Microsoft Corporation
qt.scenegraph.general: GL_RENDERER:       D3D12 (Intel(R) Iris(R) Xe Graphics)
qt.scenegraph.general: GL_VERSION:        4.1 (Compatibility Profile) Mesa 23.0.4-0ubuntu1~22.04.1
qt.scenegraph.general: GL_EXTENSIONS:    GL_AMD_conservative_depth GL_AMD_draw_buffers_blend GL_AMD_multi_draw_indirect GL_AMD_shader_stencil_export GL_AMD_shader_trinary_minmax GL_AMD_texture_texture4 GL_ANGLE_texture_compression_dxt3 GL_ANGLE_texture_compression_dxt5 GL_APPLE_packed_pixels GL_ARB_ES2_compatibility GL_ARB_ES3_compatibility GL_ARB_arrays_of_arrays GL_ARB_base_instance GL_ARB_blend_func_extended GL_ARB_buffer_storage GL_ARB_clear_buffer_object GL_ARB_clip_control GL_ARB_color_buffer_float GL_ARB_compatibility GL_ARB_compressed_texture_pixel_storage GL_ARB_conditional_render_inverted GL_ARB_conservative_depth GL_ARB_copy_buffer GL_ARB_debug_output GL_ARB_depth_buffer_float GL_ARB_depth_clamp GL_ARB_depth_texture GL_ARB_direct_state_access GL_ARB_draw_buffers GL_ARB_draw_buffers_blend GL_ARB_draw_elements_base_vertex GL_ARB_draw_indirect GL_ARB_draw_instanced GL_ARB_explicit_attrib_location GL_ARB_explicit_uniform_location GL_ARB_fragment_coord_conventions GL_ARB_fragment_layer_viewport GL_ARB_fragment_program GL_ARB_fragment_program_shadow GL_ARB_fragment_shader GL_ARB_framebuffer_no_attachments GL_ARB_framebuffer_object GL_ARB_framebuffer_sRGB GL_ARB_get_program_binary GL_ARB_get_texture_sub_image GL_ARB_gpu_shader5 GL_ARB_gpu_shader_fp64 GL_ARB_gpu_shader_int64 GL_ARB_half_float_pixel GL_ARB_half_float_vertex GL_ARB_indirect_parameters GL_ARB_instanced_arrays GL_ARB_internalformat_query GL_ARB_internalformat_query2 GL_ARB_invalidate_subdata GL_ARB_map_buffer_alignment GL_ARB_map_buffer_range GL_ARB_multi_bind GL_ARB_multi_draw_indirect GL_ARB_multisample GL_ARB_multitexture GL_ARB_occlusion_query GL_ARB_occlusion_query2 GL_ARB_parallel_shader_compile GL_ARB_pixel_buffer_object GL_ARB_point_parameters GL_ARB_point_sprite GL_ARB_program_interface_query GL_ARB_provoking_vertex GL_ARB_robust_buffer_access_behavior GL_ARB_robustness GL_ARB_sample_shading GL_ARB_sampler_objects GL_ARB_seamless_cube_map GL_ARB_separate_shader_objects GL_ARB_shader_atomic_counter_ops GL_ARB_shader_atomic_counters GL_ARB_shader_bit_encoding GL_ARB_shader_draw_parameters GL_ARB_shader_objects GL_ARB_shader_precision GL_ARB_shader_stencil_export GL_ARB_shader_storage_buffer_object GL_ARB_shader_subroutine GL_ARB_shader_texture_lod GL_ARB_shading_language_100 GL_ARB_shading_language_420pack GL_ARB_shading_language_include GL_ARB_shading_language_packing GL_ARB_shadow GL_ARB_stencil_texturing GL_ARB_sync GL_ARB_tessellation_shader GL_ARB_texture_border_clamp GL_ARB_texture_buffer_object GL_ARB_texture_buffer_object_rgb32 GL_ARB_texture_buffer_range GL_ARB_texture_compression GL_ARB_texture_compression_bptc GL_ARB_texture_compression_rgtc GL_ARB_texture_cube_map GL_ARB_texture_cube_map_array GL_ARB_texture_env_add GL_ARB_texture_env_combine GL_ARB_texture_env_crossbar GL_ARB_texture_env_dot3 GL_ARB_texture_filter_anisotropic GL_ARB_texture_float GL_ARB_texture_gather GL_ARB_texture_mirrored_repeat GL_ARB_texture_multisample GL_ARB_texture_non_power_of_two GL_ARB_texture_query_levels GL_ARB_texture_query_lod GL_ARB_texture_rectangle GL_ARB_texture_rg GL_ARB_texture_rgb10_a2ui GL_ARB_texture_stencil8 GL_ARB_texture_storage GL_ARB_texture_storage_multisample GL_ARB_texture_swizzle GL_ARB_timer_query GL_ARB_transform_feedback2 GL_ARB_transform_feedback3 GL_ARB_transform_feedback_instanced GL_ARB_transpose_matrix GL_ARB_uniform_buffer_object GL_ARB_vertex_array_bgra GL_ARB_vertex_array_object GL_ARB_vertex_attrib_64bit GL_ARB_vertex_attrib_binding GL_ARB_vertex_buffer_object GL_ARB_vertex_program GL_ARB_vertex_shader GL_ARB_vertex_type_10f_11f_11f_rev GL_ARB_vertex_type_2_10_10_10_rev GL_ARB_viewport_array GL_ARB_window_pos GL_ATI_blend_equation_separate GL_ATI_draw_buffers GL_ATI_fragment_shader GL_ATI_separate_stencil GL_ATI_texture_env_combine3 GL_ATI_texture_float GL_EXT_EGL_image_storage GL_EXT_EGL_sync GL_EXT_abgr GL_EXT_bgra GL_EXT_blend_color GL_EXT_blend_equation_separate GL_EXT_blend_func_separate GL_EXT_blend_minmax GL_EXT_blend_subtract GL_EXT_compiled_vertex_array GL_EXT_copy_texture GL_EXT_debug_label GL_EXT_direct_state_access GL_EXT_draw_buffers2 GL_EXT_draw_instanced GL_EXT_draw_range_elements GL_EXT_fog_coord GL_EXT_framebuffer_blit GL_EXT_framebuffer_multisample GL_EXT_framebuffer_multisample_blit_scaled GL_EXT_framebuffer_object GL_EXT_framebuffer_sRGB GL_EXT_gpu_program_parameters GL_EXT_gpu_shader4 GL_EXT_memory_object GL_EXT_memory_object_fd GL_EXT_multi_draw_arrays GL_EXT_packed_depth_stencil GL_EXT_packed_float GL_EXT_packed_pixels GL_EXT_pixel_buffer_object GL_EXT_point_parameters GL_EXT_provoking_vertex GL_EXT_rescale_normal GL_EXT_secondary_color GL_EXT_semaphore GL_EXT_semaphore_fd GL_EXT_separate_specular_color GL_EXT_shader_integer_mix GL_EXT_shadow_funcs GL_EXT_stencil_two_side GL_EXT_stencil_wrap GL_EXT_subtexture GL_EXT_texture GL_EXT_texture3D GL_EXT_texture_array GL_EXT_texture_buffer_object GL_EXT_texture_compression_dxt1 GL_EXT_texture_compression_rgtc GL_EXT_texture_compression_s3tc GL_EXT_texture_cube_map GL_EXT_texture_edge_clamp GL_EXT_texture_env_add GL_EXT_texture_env_combine GL_EXT_texture_env_dot3 GL_EXT_texture_filter_anisotropic GL_EXT_texture_integer GL_EXT_texture_lod_bias GL_EXT_texture_object GL_EXT_texture_rectangle GL_EXT_texture_sRGB GL_EXT_texture_sRGB_decode GL_EXT_texture_shared_exponent GL_EXT_texture_snorm GL_EXT_texture_swizzle GL_EXT_timer_query GL_EXT_transform_feedback GL_EXT_vertex_array GL_EXT_vertex_array_bgra GL_EXT_vertex_attrib_64bit GL_IBM_multimode_draw_arrays GL_IBM_rasterpos_clip GL_IBM_texture_mirrored_repeat GL_INGR_blend_func_separate GL_KHR_context_flush_control GL_KHR_debug GL_KHR_no_error GL_KHR_parallel_shader_compile GL_KHR_robust_buffer_access_behavior GL_KHR_robustness GL_KHR_texture_compression_astc_ldr GL_KHR_texture_compression_astc_sliced_3d GL_MESA_pack_invert GL_MESA_shader_integer_functions GL_MESA_texture_signed_rgba GL_MESA_window_pos GL_NV_ES1_1_compatibility GL_NV_blend_square GL_NV_conditional_render GL_NV_copy_image GL_NV_depth_clamp GL_NV_fog_distance GL_NV_half_float GL_NV_light_max_exponent GL_NV_packed_depth_stencil GL_NV_primitive_restart GL_NV_texgen_reflection GL_NV_texture_env_combine4 GL_NV_texture_rectangle GL_NV_vdpau_interop GL_OES_EGL_image GL_OES_read_format GL_S3_s3tc GL_SGIS_generate_mipmap GL_SGIS_texture_border_clamp GL_SGIS_texture_edge_clamp GL_SGIS_texture_lod GL_SUN_multi_draw_arrays
qt.scenegraph.general: Max Texture Size: 16384
qt.scenegraph.general: Debug context:    false
```

Forcing OpenGL version to 3.1 does not help.

Here's my `glxinfo | grep -i opengl`: 

```
OpenGL vendor string: Microsoft Corporation
OpenGL renderer string: D3D12 (Intel(R) Iris(R) Xe Graphics)
OpenGL core profile version string: 4.1 (Core Profile) Mesa 23.0.4-0ubuntu1~22.04.1
OpenGL core profile shading language version string: 4.10
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 4.1 (Compatibility Profile) Mesa 23.0.4-0ubuntu1~22.04.1
OpenGL shading language version string: 4.10
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.0 Mesa 23.0.4-0ubuntu1~22.04.1
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.00
OpenGL ES profile extensions:
```

I have Iris Xe on i7-1360P, Intel Driver version 31.0.101.5081 (updated to the latest one yesterday, still did not fix the issue)

I think that the problem is with the Intel Driver somehow

**Comment by Leojangh** [comment]
I had this glitch after I moved my distro to annother disk(using `wsl --export` and then `wsl --import`),but it cannot repreduce when i restarted my PC.

**Comment by ArchemedIan** [comment]
> > I guess this might work: End task of WSL from task manager and open Ecmas or whatever app you want to use from start menu (not through terminal)
> 
> i dont understand. how can i open a wsl app from the hosts start menu?

... Click on the app icon?

**Comment by Majixed** [comment]
I had this problem after exporting my WSL distro to an external disk, and it would only occur after I closed the terminal, waited for a bit, and reopened it again. Then when I start a GUI application, it would show [WARN: COPY MODE] in the title bar when I hover over it in the taskbar, and said corruption would occur when I try to perform any action in the GUI app. Today I set my HDD to stop automatically sleeping after 1 minute of inactivity, and this problem seems to have disappeared completely. So I think it had something to do with the HDD going to sleep while WSL was still running in the background.

**Comment by Frumious** [comment]
I just installed a fresh copy of WSL on a new laptop with the default Ubuntu 22.04 and ran into this with emacs in a gui window.

I upgraded to ubuntu 23.04 (`sudo do-release-upgrade`), rebooted, and the problem was fixed. I normally the latest Ubuntu, so this was just a pitstop on the way to 23.10. If you really need 22.04, you'll need another solution, but if you just want it to work, upgrading ubuntu seems to do the trick.

**Comment by jonkerw85** [comment]
I also encounter this problem on my laptop with up-to-date Intel arc driver (v31.0.101.5084) on Ubuntu 20.04. For example, running xeyes resulted in glitches. During  movements or resizing of xeyes window the glitches temporarily stop.


WSL-versie: 2.0.9.0
Kernelversie: 5.15.133.1-1
WSLg-versie: 1.0.59
MSRDC-versie: 1.2.4677
Direct3D-versie: 1.611.1-81528511
DXCore-versie: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows-versie: 10.0.19045.3693

**Comment by markeissler** [comment]
Just setting up a brand new Windows 11 Pro workstation and I'm seeing this problem with Ubuntu 22.04 as well.
<img width="134" alt="Screenshot 2024-01-05 102725" src="https://github.com/microsoft/wslg/assets/2679087/16ef984d-3f12-4bfc-88b1-59ff2338c012">

<img width="645" alt="Screenshot 2024-01-05 104747" src="https://github.com/microsoft/wslg/assets/2679087/c7b02040-4418-4679-afb8-8907cc19ae96">

Haven't tried upgrading to 23.04 as I'm waiting to see more feedback on that from others.

**Comment by PikalaxALT** [comment]
> I tried:
> 
> * Updated nvidia drivers (via "GeForce Experience")
> * `sudo apt update`
> * `sudo apt upgrade`
> * `wsl --shutdown` via PowerShell (Admin)
> 
> Then it worked until a restart.
> 
> Identified that after boot I manually once always need to run `wsl --shutdown`, then reopen wsl and it works from then on until the next restart.
> 
> I can't downgrade at the moment and am waiting for an official fix (see #1130).

Experiencing the same issue. This works as a temporary fix.

**Comment by torzdf** [comment]
I'll add a "me too" to this.

In my testing, this impacts *all* WSL2 distros, but it does not always happen (it just happens most of the time).

I have tested the fixes above, and whilst it sometimes appears to have fixed the issue, the reality (for me) was that it was just coincidence, and the glitch had not happened to hit on that occasion. When I re-open the app later, then the issue may or may not have returned, but at some point it will return.

It would be great if there was some acknowledgement here that there is an issue and whether it will or will not be addressed. My usecase is I need to package an app that uses WSL2, and I cannot realistically release unless this issue gets fixed (or unless the is acknowledgement that it won't be fixed and I will need to look for a workaround with a 3rd party X-client).

**Comment by rudeq** [comment]
Another me too added. Come on Microsoft, you break it, you fix it. It's been more than 2 months

**Comment by arti5an** [comment]
Another "me too". I seem to be able to launch QT applications reliably however, so thankfully was able to swap out my pinentry from the gtk to qt flavour. I'm using NixOS under WSL too, which demonstrates (as others have found) that it's not just Ubuntu. Annoyingly it breaks VS Code within WSL, and in fact anything I've tried that I know uses Electron. Weirdly when it does happen, moving the affected window about seems to fix it temporarily _while moving_, then it breaks once you _drop it_.

All seems to suggest it's a host level problem to me, but QT (probably an old version) pinentry working suggests maybe that's a modern graphics acceleration feature that's broken _maybe..._?

**Comment by snowgato** [comment]
running wsl2 on ubuntu22.04
adding LIBGL_ALWAYS_SOFTWARE=1 to .wslconfig just temporarly solved the issue, now it's back

I've finally installed mobaXterm on windows,
then modified ~/.bashrc adding the following line:
export DISPLAY="$(/sbin/ip route | awk '/default/ { print $3 }'):0"

on mobaXterm, I did Setttings>Configuration>X11tab>Set X11 remote access to full to skip dialog confirmationsto enable X11 connection
 
with mobaXterm connections allowed only on private network

and that works, 10 min to do it

**Comment by arti5an** [comment]
Thanks for the pointer/idea @snowgato. I did a bit of digging around the wslg repo and found mention of various config options in the [wiki](/microsoft/wslg/wiki/WSLg-Configuration-Options-for-Debugging). Near the bottom is the option to force software rendering, which seems to at least circumvent the issue for me. These options don't belong in `.wslconfig` however; they should be in `.wslgconfig` (note the **g**). In my case I entered the following, and after restarting WSL it seems to work:

```
[system-distro-env]
LIBGL_ALWAYS_SOFTWARE=1
```

**Comment by snowgato** [comment]
This setting also worked for me for a couple days, and this morning the glitches were back.
Maybe Microsoft team will solve this issue in a few months, who knows ?

**Comment by arti5an** [comment]
The wiki entry also suggests `LIBGL_ALWAYS_SOFTWARE=1` also needs exporting from your OS. At least initially it seemed to work _without_ that for me, however I wonder if it might affect certain apps, e.g. thinking the OS has hardware acceleration when it doesn't... 🤷 As more of a precaution than anything, I have since exported it just in case... Maybe that could work for you @snowgato? 🤞

**Comment by snowgato** [comment]
What do you mean by exporting ?
I had just modified .wslconfig by adding 
LIBGL_ALWAYS_SOFTWARE=1

**Comment by arti5an** [comment]
Sorry, I mean export a variable. Where you'd do that is somewhat distro/config dependent, but mostly if you put `export LIBGL_ALWAYS_SOFTWARE="1"` in a new file `/etc/profile.d/wsl-workaround.sh`, restart WSL and try `echo $LIBGL_ALWAYS_SOFTWARE`. If it reports the `1` then it worked. If not, try adding the line to `/etc/profile` (after what's already in it) instead.

If you only tried `.wslconfig` as you mention, it might be worth trying `.wslgconfig` instead. It could be MS renamed the config specifically for the WSLg component, although MS do _tend_ to maintain backward compatibility where they can. 🤷

**Comment by snowgato** [comment]
thanks for the suggestions, but I am not going to lose time anymore searching what could work as it already works with mobaXterm, as long as mobaXterm stays free :-)

**Comment by stolsvik** [comment]
Just a chip-in: Have everyone tried the `wsl --shutdown` trick? https://github.com/microsoft/wslg/issues/1148#issuecomment-1826238058

I did, and it worked: Just shutdown, and then startup again, and suddenly no problems anymore.

(I've used `xeyes` as the test app. This is fine as long as you don't have your mouse pointer at it, but when you put it inside the window, it "crashes" visually like we're talking about here. But then it is fine again when I take the mouse pointer out of the window)

**Comment by brunobernardnh** [comment]
For me wsl --shutdown trick works good. The issue rarely happen to me but when it does i just shutdown and restart.
Hope this get fixed soon thought

**Comment by tkonsta** [comment]
A small addition to the `wsl --shutdown` workaround:
I've experienced, that if the small script mentioned in https://github.com/microsoft/wslg/issues/972#issuecomment-1737468490 brings up the error message, then the glitches happen. The two problems seem to be related. So what I did as an fail-early mechanism, is, that I added the script from the mentioned comment to my `.bashrc` and whenever I see it showing up, then I restart WSL and in most cases the problem is gone after one restart. Sometimes it needs another restart, but eventually the error disappears and there are no more glitches.

**Comment by sv1day** [comment]
It worked for me too! Thank you very much!

**Comment by mwoodpatrick** [comment]
I hit the same issue when running 

```
virt-manager 4.1.0
virt-install 4.1.0
QEMU emulator version 8.2.0
```

My config:

```
WSL version: 2.1.0.0
Kernel version: 5.15.137.3-1
WSLg version: 1.0.59
MSRDC version: 1.2.4677
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22635.3061
Kernel: 6.1.21.2-microsoft-standard-WSL2+
```

I tried running with MobaXterm but I still hit the same issue, I tried running with VcXsrv but could not get the apps to connect with that so far, still investigating why that option is not working.

**Comment by jo-37** [comment]
None of the suggestions worked for me. However, I found a completely different workaround: If the wsl vm start is initiated by running a native linux-gui application (here: lxterminal), then everything runs fine. (No x-server is running in wsl.)

**Comment by SirLouen** [comment]
The `wsl --shutdown` is working for me but the `%USERPROFILE%` `.wslgconfig` is not. I'm sitting on a RTX3060. Not sure if this only works for other type of GPU

**Comment by KarlHoffm** [comment]
same problem, running nautilus and getting visual bugs, fixed by following this:

>In .wslgconfig I added 
> 
> > [system-distro-env]
> > ;disable GPU in system-distro
> > LIBGL_ALWAYS_SOFTWARE=1
> 
> -Restarted wsl. Worked. -Restarted laptop, the fix still works.
> 
> Maybe other people try this and post their feedback.

.wslgconfig goes to C:\ProgramData\Microsoft\WSL

my config
>WSL version: 2.0.9.0
>Kernel version: 5.15.133.1-1
>WSLg version: 1.0.59
>MSRDC version: 1.2.4677
>Direct3D version: 1.611.1-81528511
>DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
>Windows version: 10.0.22621.3007

**Comment by Omega3LokO** [comment]
> Same issue here. Windows 11 with following WSL info
> 
> > WSL version: 2.0.9.0
> > Kernel version: 5.15.133.1-1
> > WSLg version: 1.0.59
> > MSRDC version: 1.2.4677
> > Direct3D version: 1.611.1-81528511
> > DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
> > Windows version: 10.0.22631.2715
> 
> I did an update in Intel Drivers update and Windows Update simultaneously so not sure what broke it. However, I tried the following:
> 
> -In .wslgconfig I added
> 
> > [system-distro-env]
> > ;disable GPU in system-distro
> > LIBGL_ALWAYS_SOFTWARE=1
> 
> -Restarted wsl. Worked. -Restarted laptop, the fix still works.
> 
> Maybe other people try this and post their feedback.

Worked for me! I added the file .wslgconfig inside the path C:\ProgramData\Microsoft\WSL  I've to create the WSL folder.

**Comment by biggestsonicfan** [comment]
Chiming in to say `wsl --shutdown` did not work for me but 
```
[system-distro-env]
;disable GPU in system-distro
LIBGL_ALWAYS_SOFTWARE=1
```
in `%USERPROFILE%/.wslgconfig` did work!

**Comment by vielhuber** [comment]
Both `C:\ProgramData\Microsoft\WSL\.wslgconfig` and `%USERPROFILE%/.wslgconfig` did not work.

Only `wsl --shutdown` works for me.

Anybody else?

**Comment by gil-ribeiro** [comment]
Adding a thumbs up too all of the above. Been using the wsl --shutdown workaround and seems to be okay for now. Using Codelite.

WSL version: 2.0.14.0
Kernel version: 5.15.133.1-1
WSLg version: 1.0.59
MSRDC version: 1.2.4677
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22621.3007

Nvidia T500 on a Windows 11 laptop

**Comment by 38leinaD** [comment]
Is there any other idea what might be the cause of the issue? Nothing described here works for me to remove the glitches. I tried, LIBGL_ALWAYS_SOFTWARE=1, wsl --shudown and then running from windows menu an app like lxterminal. Glitches are still there.

**Comment by VincentSch4rf** [comment]
The only thing that worked for me was upgrading to the pre-release `2.1.1.0` as suggested by @38leinaD.

**Comment by guokeme** [comment]
My wsl version information is as follows:
![image](https://github.com/microsoft/wslg/assets/12101271/81c192e0-f02f-4588-8c67-fa3203c59dfd)
After my repeated testing, I can determine the following:
1. When I use the wsl -t Ubuntu-22.04 command to terminate my Ubuntu, and then restart the GUI program, a blurred screen will appear;
2. When I use the wsl --shutdown command to terminate my wsl, and then restart the GUI program, there will be no blurred screen;
So it can be speculated that this bug is caused by the wsl -t command, and this command may also be used when the Windows system is shut down, thus causing the bug. I hope this comment will be seen.

**Comment by guokeme** [comment]
> My wsl version information is as follows: ![image](https://private-user-images.githubusercontent.com/12101271/302084761-81c192e0-f02f-4588-8c67-fa3203c59dfd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcwMzM0NDQsIm5iZiI6MTcwNzAzMzE0NCwicGF0aCI6Ii8xMjEwMTI3MS8zMDIwODQ3NjEtODFjMTkyZTAtZjAyZi00NTg4LThjNjctZmEzMjAzYzU5ZGZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA0VDA3NTIyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI0NmVhMzhkM2JhMzAwYWM1ODQzODc2NWI4ZTJlYTJmNDNjZWMwNjgxMzNiNTk5YTk4NmMwMzc2NTA1NjlhODcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.z3XlaGSiZJkDDC0QFYHk59QQN987o1_bc6k8a9nBChY) After my repeated testing, I can determine the following:
> 
> 1. When I use the wsl -t Ubuntu-22.04 command to terminate my Ubuntu, and then restart the GUI program, a blurred screen will appear;
> 2. When I use the wsl --shutdown command to terminate my wsl, and then restart the GUI program, there will be no blurred screen;
>    So it can be speculated that this bug is caused by the wsl -t command, and this command may also be used when the Windows system is shut down, thus causing the bug. I hope this comment will be seen.

Also, this happens when I reopen the GUI program after using the poweroff command on the Ubuntu command line.

**Comment by abudabid** [comment]
> Same issue here. Windows 11 with following WSL info
> 
> > WSL version: 2.0.9.0
> > Kernel version: 5.15.133.1-1
> > WSLg version: 1.0.59
> > MSRDC version: 1.2.4677
> > Direct3D version: 1.611.1-81528511
> > DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
> > Windows version: 10.0.22631.2715
> 
> I did an update in Intel Drivers update and Windows Update simultaneously so not sure what broke it. However, I tried the following:
> 
> -In .wslgconfig I added
> 
> > [system-distro-env]
> > ;disable GPU in system-distro
> > LIBGL_ALWAYS_SOFTWARE=1
> 
> -Restarted wsl. Worked. -Restarted laptop, the fix still works.
> 
> Maybe other people try this and post their feedback.

It worked !

**Comment by krych14m** [comment]
WSL version 2.0.9.0: glitches occur.
WSL version 2.0.9.0 with "LIBGL_ALWAYS_SOFTWARE=1" option: glitches disappeared, but then appear suddenly, I see no pattern. WSL restart works.
WSL version 2.0.14.0: glitches dissapeared!!! :D

**Comment by snowgato** [comment]
WSL version 2.1.1.0 seems to work !
WSL version 2.1.0.14 didn't solve the issue for me

**Comment by biggestsonicfan** [comment]
> Chiming in to say `wsl --shutdown` did not work for me but
> 
> ```
> [system-distro-env]
> ;disable GPU in system-distro
> LIBGL_ALWAYS_SOFTWARE=1
> ```
> 
> in `%USERPROFILE%/.wslgconfig` did work!

Coming back to say I am encountering this again.  `%USERPROFILE%/.wslgconfig` no longer works and `wsl --shutdown` still does not work for me.

Specs:
```
WSL version: 2.0.14.0
Kernel version: 5.15.133.1-1
WSLg version: 1.0.59
MSRDC version: 1.2.4677
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.19045.3996
```

**Comment by arti5an** [comment]
> Sorry, I mean export a variable. Where you'd do that is somewhat distro/config dependent, but mostly if you put `export LIBGL_ALWAYS_SOFTWARE="1"` in a new file `/etc/profile.d/wsl-workaround.sh`, restart WSL and try `echo $LIBGL_ALWAYS_SOFTWARE` it _should_ report `1`. If it doesn't then try adding the line to `/etc/profile` (after what's already in it) instead.
> 
> If you only tried `.wslconfig` as you mention, it might be worth trying `.wslgconfig` instead. It could be MS renamed the config specifically for the WSLg component, although MS do _tend_ to maintain backward compatibility where they can. 🤷

Following on from my earlier post, having seen several mentions of newer versions of WSL, I updated around a week ago to the prerelease using `wsl --update --pre-release`. I then removed my `.wslgconfig` file and my `.wslconfig` file (since it only had a setting to enable the GUI, and it's on by default nowadays), rebooted my laptop and tried a few GUI apps. I'm happy to report that the issue seems to have been resolved for me, and can confirm it is reporting version `2.1.1.0`. Thankfully I don't seem to have encountered any additional issues despite the pre-release moniker. 😄

**Comment by cgagnon-crakmn** [comment]
This is interesting how you solved your issues with
```
[system-distro-env]
;disable GPU in system-distro
LIBGL_ALWAYS_SOFTWARE=1
```

My WSL version
```
WSL version: 2.0.14.0
Kernel version: 5.15.133.1-1
WSLg version: 1.0.59
MSRDC version: 1.2.4677
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.19045.4046
```

I did it with
```
[wsl2]
gpuSupport=false
```
I found out about this option at https://github.com/microsoft/WSL/issues/8931

I never had the glitch ever again.

**Comment by mateialexandru** [comment]
> Solution that worked for me now (nothing else described above worked): `wsl --update --pre-release` version is now: `wsl --version` WSL version: 2.1.1.0 Kernel version: 5.15.146.1-2 WSLg version: 1.0.60 MSRDC version: 1.2.5105 Direct3D version: 1.611.1-81528511 DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp Windows version: 10.0.19045.3930

thank you, this worked!

**Comment by evgenybf** [comment]
> Just a chip-in: Have everyone tried the `wsl --shutdown` trick? [#1148 (comment)](https://github.com/microsoft/wslg/issues/1148#issuecomment-1826238058)
> 
> I did, and it worked: Just shutdown, and then startup again, and suddenly no problems anymore.

Sometimes it also requires killing "wslservice.exe" from Task Manager.

**Comment by teleskier1** [comment]
> > Solution that worked for me now (nothing else described above worked): `wsl --update --pre-release` version is now: `wsl --version` WSL version: 2.1.1.0 Kernel version: 5.15.146.1-2 WSLg version: 1.0.60 MSRDC version: 1.2.5105 Direct3D version: 1.611.1-81528511 DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp Windows version: 10.0.19045.3930
> 
> thank you, this worked!

This worked for me as well. Thank you!

**Comment by TheNavyBear** [comment]
What worked for me: 'sudo apt install dbus-x11'

Not sure why it is not installed in WSL2 when an x11/GUI app is installed, but installing it fixed all my GUI apps, including ones that wouldn't open.

**Comment by biggestsonicfan** [comment]
> What worked for me: 'sudo apt install dbus-x11'

@TheNavyBear, did that fix a specific GUI app or all GUI apps?

**Comment by kdavisee** [comment]
> -In .wslgconfig I added
> 
> > [system-distro-env]
> > ;disable GPU in system-distro
> > LIBGL_ALWAYS_SOFTWARE=1
> 
> -Restarted wsl. Worked. -Restarted laptop, the fix still works.
> 
> Maybe other people try this and post their feedback.

I think this is the solution to my problem but I am too dumb to understand what I need to do : (  

I don't know what it means to add things or how to open wslgconfig, any help on what I need to type?

**Comment by Sherry65-code** [comment]
I was developing my Game engine and decided to use WSL (Debian) to test my engine. It opened but when the window frame would not update it was cause the lining issues, many people see above. but doing a `wsl --shutdown` and then reopning wsl fixes the issue. Luckily! :)

**Comment by TheNavyBear** [comment]
> > What worked for me: 'sudo apt install dbus-x11'
> 
> @TheNavyBear, did that fix a specific GUI app or all GUI apps?

That fixed the glitch artifacts in my GUI apps, it fixed issues where preferences couldn't be set in GNOME apps, and it fixed two apps that wouldn't even open. This was the case on all 3 of my Debian WSL2 systems.

**Comment by nikosandreou** [comment]
> > -In .wslgconfig I added
> > > [system-distro-env]
> > > ;disable GPU in system-distro
> > > LIBGL_ALWAYS_SOFTWARE=1
> > 
> > 
> > -Restarted wsl. Worked. -Restarted laptop, the fix still works.
> > Maybe other people try this and post their feedback.
> 
> I think this is the solution to my problem but I am too dumb to understand what I need to do : (
> 
> I don't know what it means to add things or how to open wslgconfig, any help on what I need to type?

@kdavisee What you have to do is to go to your windows user folder and create the file. 

1) Open windows file explorer and type %USERPROFILE% in the address bar
2) This will open the user profile folder in your PC/Laptop
3) There you must create a new file named .wslgconfig (yes, with the dot in the beginning)
4) Add the content that I typed before. 
5) Restart WSL (in a powershell type wsl --shutdown and then open terminal again or better restart laptop/pc)

**Comment by 0xilham** [comment]
> I tried:
> 
> * Updated nvidia drivers (via "GeForce Experience")
> * `sudo apt update`
> * `sudo apt upgrade`
> * `wsl --shutdown` via PowerShell (Admin)
> 
> Then it worked until a restart.
> 
> Identified that after boot I manually once always need to run `wsl --shutdown`, then reopen wsl and it works from then on until the next restart.
> 
> I can't downgrade at the moment and am waiting for an official fix (see #1130).

Thanks, this worked

**Comment by biggestsonicfan** [comment]
Can someone here explain the difference between restarting the computer, a full Windows reboot, and `wsl --shutdown`? Would a reboot not entail wsl closing and upon starting the terminal again on a fresh boot act as a new instance of wsl starting up?

**Comment by Potak0** [comment]
> Same issue here. Windows 11 with following WSL info
> 
> > WSL version: 2.0.9.0
> > Kernel version: 5.15.133.1-1
> > WSLg version: 1.0.59
> > MSRDC version: 1.2.4677
> > Direct3D version: 1.611.1-81528511
> > DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
> > Windows version: 10.0.22631.2715
> 
> I did an update in Intel Drivers update and Windows Update simultaneously so not sure what broke it. However, I tried the following:
> 
> -In .wslgconfig I added
> 
> > [system-distro-env]
> > ;disable GPU in system-distro
> > LIBGL_ALWAYS_SOFTWARE=1
> 
> -Restarted wsl. Worked. -Restarted laptop, the fix still works.
> 
> Maybe other people try this and post their feedback.

worked. a big thank for you.
note: if .wslgconfig is not found in system,  applying the same solution to ubuntu  /etc/wsl.conf works too.

**Comment by shusuke-ethic** [comment]
creating the .wslgconfig worked. looking forward to the next release with the fix.

**Comment by nikosandreou** [comment]
> creating the .wslgconfig worked. looking forward to the next release with the fix.

You can update to latest wsl where the issue is fixed (2.1.5). Just run in powershell as admin 

`wsl --update`

**Comment by pirafrank** [comment]
I guess this issue can be closed, as we now have a stable version fixing it (`v2.1.5`).

**Comment by shusuke-ethic** [comment]
I confirmed the following version combination works, without the .wslgconfig file. I'm ok you close this issue.

> WSL version: 2.1.5.0
Kernel version: 5.15.146.1-2
WSLg version: 1.0.60
MSRDC version: 1.2.5105
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22621.3296

**Comment by bestis** [comment]
Nah. Still seeing glitches.. 
```
>wsl --version
WSL version: 2.1.5.0
Kernel version: 5.15.146.1-2
WSLg version: 1.0.60
MSRDC version: 1.2.5105
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22631.3593
```

![image](https://github.com/microsoft/wslg/assets/1753286/16ca58c8-5495-4772-ac13-98a1d0412f83)

I did add to .wslgconfig
```
;disable GPU in system-distro
LIBGL_ALWAYS_SOFTWARE=1
```
But this seems just to make it work before the Chromium loads the tab, maybe just lucky and didn't notice before. Then I can see the tab, but when it has loaded, all broken. I need to launch the Chromium itself with `--disable-gpu`.

Lenovo X1 Carbon Gen13, so Intel integrated graphics. No NVIDIA to update. Intel would seem to have later drivers to download manually but nothing offers them automatically. So don't know what problems I would get there from not using OEM drivers. And the `31.0.101.5234` is the latest OEM driver from 11 Mar 2024.

**Comment by ensapra** [comment]
https://github.com/user-attachments/assets/46478bee-3b4f-4df2-b18a-f2c26de19cd8

Is this the same issue?

**Comment by thendricks0** [comment]
I have these strange crossed out artifacts on some gui applications.

The search bar in the title of vscode for example shows this issue:
![Image](https://github.com/user-attachments/assets/7e405350-7010-4aa8-9893-91ad14266131)

The vscode icon also looks like this in the title bar:
![Image](https://github.com/user-attachments/assets/d9f5f508-f7e7-470f-81cd-57c4238dd729)

If I use some icon extensions like Material Icon Theme or vscode-icons all the icons show the same weird artifact which makes the icons hard to recognize:
![Image](https://github.com/user-attachments/assets/a0a3032d-4992-47b6-a87f-3dc3b6b45510)

The Jetbrains toolbox also displays this artifact so it is not VSCode related:
![Image](https://github.com/user-attachments/assets/25a9126c-d4da-4093-a9ed-376f3a21f5d4)


I've compared the icon file formats in the icon themes and the properly displayed icons are in png format while the icons with the cross artifact are in svg format. So is this a scaling issue with vector images? Is there a workaround for this maybe?

**Comment by nikosandreou** [comment]
> I have these strange crossed out artifacts on some gui applications.
> 
> The search bar in the title of vscode for example shows this issue: ![Image](https://github.com/user-attachments/assets/7e405350-7010-4aa8-9893-91ad14266131)
> 
> The vscode icon also looks like this in the title bar: ![Image](https://github.com/user-attachments/assets/d9f5f508-f7e7-470f-81cd-57c4238dd729)
> 
> If I use some icon extensions like Material Icon Theme or vscode-icons all the icons show the same weird artifact which makes the icons hard to recognize: ![Image](https://github.com/user-attachments/assets/a0a3032d-4992-47b6-a87f-3dc3b6b45510)
> 
> The Jetbrains toolbox also displays this artifact so it is not VSCode related: ![Image](https://github.com/user-attachments/assets/25a9126c-d4da-4093-a9ed-376f3a21f5d4)
> 
> I've compared the icon file formats in the icon themes and the properly displayed icons are in png format while the icons with the cross artifact are in svg format. So is this a scaling issue with vector images? Is there a workaround for this maybe?

I think this may be related to the above. It was an instant alarm to the issue I have:

https://github.com/shiftkey/desktop/issues/1009

Since github-desktop is an electon app (chromium based), this could be related.

**Comment by thendricks0** [comment]
@nikosandreou thanks for linking to your issue, your hint on downgrading the Intel Graphics drivers was very useful!

Since my laptop has an NVIDIA dGPU I simply used `export MESA_D3D12_DEFAULT_ADAPTER_NAME=NVIDIA` to force the usage of the NVIDIA GPU which does NOT have this weird rendering issue. So it seems this is an Intel driver related problem.

**Comment by computergeek125** [comment]
This definitely seems hardware acceleration related.

Reproducible on Intel 32.0.101.6314 (windows update) (and probably several others, just found this issue) and 32.0.101.6795 (Intel DSA)

Immediately after installing 6795, it appeared to work, but after cycling a `wsl --shutdown` the issure recured so I believe it was only "working" due to whatever inconsistency/lost render handle that occurred during the act of upgrading the driver
