### ISSUE TITLE
Can't open display error when trying to launch apps

### ISSUE THREAD

**Issue by mickaelchanrion** [microsoft/wslg#134]
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.21370.1]
Your Distribution version: Ubuntu 20.04
Your WSLg version: 1.0.17.1
```

# Steps to reproduce

- wsl --update (on my existing ubuntu distro in wsl2)
- install x11-apps and google-chrome
- launch xcalc / xclock / xeyes : I get "Error: Can't open display: 127.0.0.1:0"
- launch google-chrome: I get "[517:517:0430/101516.333068:ERROR:browser_main_loop.cc(1386)] Unable to open X display." 

Thinking that there might be a misconfig in my distro, I tried to test wslg with a fresh ubuntu distro, but same result...

**Please note**: I followed this blog post 2 months ago to try to get google-chrome running
https://techcommunity.microsoft.com/t5/windows-dev-appconsult/running-wsl-gui-apps-on-windows-10/ba-p/1493242
I could launch basic apps like xcalc but couldn't launch google-chrome
Then I uninstalled VcXsrv. 

**WSL logs**: 

* `puseaudio.log`
W: [pulseaudio] authkey.c: Failed to open cookie file '/home/wslg/.config/pulse/cookie': No such file or directory
W: [pulseaudio] authkey.c: Failed to load authentication key '/home/wslg/.config/pulse/cookie': No such file or directory
W: [pulseaudio] authkey.c: Failed to open cookie file '/home/wslg/.pulse-cookie': No such file or directory
W: [pulseaudio] authkey.c: Failed to load authentication key '/home/wslg/.pulse-cookie': No such file or directory
E: [pulseaudio] module-console-kit.c: GetSessionsForUnixUser() call failed: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.ConsoleKit was not provided by any .service files
E: [pulseaudio] module.c: Failed to load module "module-console-kit" (argument: ""): initialization failed.
E: [rdp-sink] module-rdp-sink.c: RDP Sink - Trying to connect to /mnt/wslg/PulseAudioRDPSink
E: [rdp-sink] module-rdp-sink.c: Connected failed
E: [rdp-sink] module-rdp-sink.c: RDP Sink - Trying to connect to /mnt/wslg/PulseAudioRDPSink
E: [rdp-sink] module-rdp-sink.c: Connected failed

* `weston.log`
File is quite big, please see the attached file.
[weston.log](https://github.com/microsoft/wslg/files/6404316/weston.log)

* `versions.txt`
WSLg ( x86_64 ): 1.0.17+3.Branch.master.Sha.a526dfd5ad03d126bb2d8c528f6c3563e86a40da
Mariner: VERSION="1.0.20210224"
FreeRDP: e4a2fc2053bd8c5f99455fcd08ffee7e5591567a
weston: fd961f5cd116c9358d82ce94d139c1578e21bd00
pulseaudio: 2f0f0b8c3872780f15e275fc12899f4564f01bd5
mesa:

#  Expected behavior

Launch the gui apps

# Actual behavior

Gettings errors

**Comment by smallst** [comment]
do you restart your wsl?

**Comment by spronovo** [comment]
Thanks for your report. You are hitting an issue in version 1.0.17 with monitor configuration (see #19)

```
weston: ../libweston/backend-rdp/rdpdisp.c:481: disp_monitor_validate_and_compute_layout: Assertion `isConnected_V == true' failed.
```

Good new is this is fixed in 1.0.19 that we just released moments ago. Open an elevated command prompt in Windows and type

```
wsl --shutdown
wsl --update
```

That should pick up 1.0.19 and your config should start working.

**Comment by mickaelchanrion** [comment]
After the update, I still have the same issue :/

**Comment by lateau** [comment]
@mickaelchanrion Which kernel version does it have now? I solved this issue by updating & force restart WSL as he described.

Reproduce:
1. Run Powershell as Administrator
2. Execute `wsl --shutdown` and `wsl --update`
3. Launch Ubuntu

```
C:\Users\***> wsl --status
Default Distribution: Ubuntu
Default Version: 2

Windows Subsystem for Linux was last updated on 5/4/2021
The Windows Subsystem for Linux kernel can be manually updated with 'wsl --update', but automatic updates cannot occur due to your system settings.
To receive automatic kernel updates, please enable the Windows Update setting: 'Receive updates for other Microsoft products when you update Windows'.
For more information please visit https://aka.ms/wsl2kernel.

Kernel version: 5.10.16
```

**Comment by mickaelchanrion** [comment]
Yes I did that, and I have the same version as you. But still not working for me

**Comment by sukehiro-San** [comment]
![Screenshot 2021-05-27 100451](https://user-images.githubusercontent.com/82700347/119767309-3961ff80-bed4-11eb-9eb2-1291d3997179.jpg)

windows build 21370
wsl 2

**Comment by spronovo** [comment]
@sukehiro-San could you take a peek at the following wiki to see where things are failing for you:

https://github.com/microsoft/wslg/wiki/Diagnosing-%22cannot-open-display%22-type-issues-with-WSLg

**Comment by dagguh** [comment]
```
Edition	Windows 10 Pro Insider Preview
Version	Dev
Installed on	‎2021-‎03-‎12
OS build	21332.1010
Experience	Windows 10 Feature Experience Pack 321.5601.0.3
```

```
PS C:\WINDOWS\system32> wsl --shutdown
PS C:\WINDOWS\system32> wsl --update
Checking for updates...
No updates are available.
Kernel version: 5.10.16
PS C:\WINDOWS\system32> wsl -l -v
  NAME                   STATE           VERSION
* Ubuntu-20.04           Stopped         2
  docker-desktop-data    Stopped         2
  docker-desktop         Stopped         2
PS C:\WINDOWS\system32> wsl

 * keychain 2.8.5 ~ http://www.funtoo.org
 * Starting ssh-agent...
 * Starting gpg-agent...

DESKTOP-OKH3D11 :: ~/src » cat /mnt/wslg
cat: /mnt/wslg: No such file or directory
```

WSLg doesn't exist.
