### ISSUE TITLE
Applications randomly become unresponsive and require a WSL restart to recover

### ISSUE THREAD

**Issue by davwheat** [microsoft/wslg#405]
# Environment

```none
Windows build number: 22000.120
Your Distribution version: Ubuntu 20.04
Your WSLg version: 1.0.24
```

# Steps to reproduce

This is the tricky part. It seems to happen randomly. I've only noticed it while using GitKraken, as that's almost the only app I use in WSLg.

**WSL logs**: 

* Attach WSLg logs from  `/mnt/wslg`

You can access the wslg logs using explorer at: `\\wsl$\<Distro-Name>\mnt\wslg` (e.g.: `\\wsl$\Ubuntu-20.04\mnt\wslg`)

- [weston.log](https://github.com/microsoft/wslg/files/6951317/weston.log)
- [pulseaudio.log](https://github.com/microsoft/wslg/files/6951318/pulseaudio.log)
- [versions.txt](https://github.com/microsoft/wslg/files/6951319/versions.txt)

#  Expected behavior

Programs work as normal.

# Actual behavior

Some applications (in my experience, it has often been while using GitKraken) unexpectedly hang on the Windows desktop. It is impossible to interact with the apps or the window itself (cannot be moved, etc.), or open any new apps afterwards.

Killing the apps with `htop` leaves the window open in Windows. A simple `wsl --shutdown`, however, does fix the issue.

NOTE: By default, `.X11-unix` is not being linked to `/mnt/wslg/.X11-unix`. I do not override `/tmp` manually. Creating the link manually fixes the issue.

**Comment by aedryan** [comment]
I'm curious if you're using Docker (and optionally devcontainers also) in conjunction with Gitkraken?  Just asking as it may be a contributing factor.  I am experiencing this same issue and working around it in the same fashion.

**Comment by davwheat** [comment]
Yes I am! I'm using Docker containers with volumes created from local folders in WSL.

The issue usually only occurs when interacting inside these folders (which is basically the only thing I use WSL for).

More recently, importantly after a full reinstall of my WSL distro, the issue with `.X11-unix` is fixed, but I still get issues with WSL. In fact it's resulting in WSL crashing as a whole. Attempting to access WSL after this results in error 0xffffffff (or whatever it is with all F's) and requires a full WSL restart.

It only happens on one of my PCs, which is a Ryzen 4000 series laptop (TongFang PN5NU1G):

- R5 4600H
- Vega integrated graphics
- 32 GB 3200 MHz Oloy RAM
- 1 TB NVMe M.2 SSD

**Comment by epiciskandar** [comment]
Same here with Intellij / Android Studio, nothing noticeable in logs, just every window stuck there, you even cannot close them.

**Comment by RiccardoManzan** [comment]
I have this same exact issue.
It is drammatic when you have to 
* stop all running processes
* stop containers
* restart everything
only to be able to reuse intellij or whatever.

Neither i found any interesting log.
I just noticed that when everything is ok i am able to kill weston process from wslg user.
When apps freeze, then i am no able to kill it.

**Comment by RiccardoManzan** [comment]
This issue keeps happening randomly for me.
I think that #472 , #539 , #605 and #645 could be related to this as nothing looks broken in logs but actually applications are freezed and cannot be moved or closed and the only solution is restarting the whole wsl.
Across those issues i collected some hypotesis:
* Docker desktop may be one of the causes
* Pulseaudio may stop responding somehow and wslg would be stuck in a IO operation
* GUI app may be placed outside desktop perimeter

Unfortunately not in all issues has been shared the stderr.log file, which could contain some crucial information.
Unfortunately again this usually happens when i have not time for debugging.

**Comment by douglasg14b** [comment]
I experience this weekly still, unfortunately sometimes `wsl --shutdown` does not resolve the issue because the shutdown command hangs as well.
