### ISSUE TITLE
Lack of Key buffer Flushing on SDL and Qt

### ISSUE THREAD

**Issue by jmacey** [microsoft/wslg#58]
# Environment

```none
 Win32NT             10.0.21364.0 Microsoft Windows NT 10.0.21364.0
Ubuntu 20 wslg 1.0.17.1
Latest Mesa distro
```

# Overview

I have noticed strange behaviour on GUI apps using both Qt and SDL2, when running first time they are fine, but on later run or different app they quit after first run. I have tracked this down to the escape key being buffered from the previous run (I use esc to quit on all my apps / demos).  To see this in action I have put a small SDL2 demo in the code below. On first run you will  not get any output. click on the window and press some keys and run again and the program will output the last events. If you try this program under other Operating systems this does not happen (Tested on windows 10 and Mac).

# Steps to reproduce

I build this program against the latest vcpk version of SDL2

```
#ifdef WIN32
    #define SDL_MAIN_HANDLED
#endif
#include <SDL2/SDL.h>
#include <cstdlib>
#include <iostream>


int main(int argc, char * argv[])
{
  // Initialize SDL's Video subsystem
  if (SDL_Init(SDL_INIT_EVERYTHING) < 0 )
  {
    // Or die on error
    exit(EXIT_FAILURE);
  }

  // now get the size of the display and create a window we need to init the video
  SDL_Rect rect;
  SDL_GetDisplayBounds(0,&rect);
  // now create our window
  SDL_Window *window=SDL_CreateWindow("SDLNGL",
                                      SDL_WINDOWPOS_CENTERED,
                                      SDL_WINDOWPOS_CENTERED,
                                      rect.w/2,
                                      rect.h/2,
                                      SDL_WINDOW_OPENGL | SDL_WINDOW_RESIZABLE | SDL_WINDOW_ALLOW_HIGHDPI
                                     );
  // check to see if that worked or exit
  if (!window)
  {
    exit(EXIT_FAILURE);
  }

  // flag to indicate if we need to exit
  bool quit=false;
  // sdl event processing data structure
  SDL_Event event;
  
  while(!quit)
  {

    while ( SDL_PollEvent(&event) )
    {
      switch (event.type)
      {
        // this is the window x being clicked.
        case SDL_QUIT : 
          quit = true;
         break;
        
        // if the window is re-sized pass it to the ngl class to change gl viewport
        // note this is slow as the context is re-create by SDL each time
        case SDL_WINDOWEVENT :
         // std::cout <<"Window event \n";
        break;

        // now we look for a keydown event
        case SDL_KEYDOWN:
        {
          switch( event.key.keysym.sym )
          {
            // if it's the escape key quit
            //case SDLK_ESCAPE :  quit = true; break;
            default : 
              std::cout<<"Key Down "<<event.key.keysym.sym<<'\n';
              std::cout<<"time stamp "<<event.key.timestamp<<'\n';

            break;
          } // end of key process
        } // end of keydown
        break;
      default : break;
      } // end of event switch
    } // end of poll events


  }
  // now tidy up and exit SDL
 SDL_Quit();
 // whilst this code will never execute under windows we need to have a return from
 // SDL_Main!
 return EXIT_SUCCESS;
}
```

First Run works fine, 2nd run will continue to print events from a queue which should have been flushed on program exit.

I'm unsure what the issue is, however I have noticed that it happens under Both SDL2 and Qt5.12 so I guess it is a wslg issue rather than an SDL / Qt one.

I can upload a minimal Qt demo if required. Attached is Simple Demo.
[SDL2Min.zip](https://github.com/microsoft/wslg/files/6364154/SDL2Min.zip)

**Comment by spronovo** [comment]
Thanks Jon for taking the time to build a small application to reproduce this problem. I've compiled the application and run it and it's working correctly for me on both 1.0.17 and the newly release 1.0.19, I'm probably missing some steps.

You mention exiting your application using the escape key... how did you configure your system to do that? Also, could you give 1.0.19 a try, we fixed an issue where some time a key would get stuck in the pressed state which may be what was happening on your end although i haven't been able to reproduce that condition with the app on my system. 

To update to 1.0.19 try the following:

```
wsl --shutdown
wsl --update
```

**Comment by JGMarshall** [comment]
I'm seeing what I believe to be a related issue with an up to date (wsl --update is current) release. However, I wouldn't characterize this as a "stuck key" per se, as the key that seems "stuck" isn't necessarily one I pressed.

Reproduction isn't obvious to me, as sometimes I can start up a gui application (such as emacs) many times without issues. However, once the condition is triggered, it happens basically constantly until I press a key in the window, which seems to stop the behavior in that window. However, the next time I start emacs, it will happen again.

xev shows a never-ending sequence of the following from my windows console bash session (two press-release pairs included to show relative timing:

```
KeyPress event, serial 34, synthetic NO, window 0x400001,
    root 0x246, subw 0x0, time 1764353, (174,-737), root:(2185,223),
    state 0x10, keycode 53 (keysym 0x78, x), same_screen YES,
    XLookupString gives 1 bytes: (78) "x"
    XmbLookupString gives 1 bytes: (78) "x"
    XFilterEvent returns: False

KeyRelease event, serial 34, synthetic NO, window 0x400001,
    root 0x246, subw 0x0, time 1764378, (174,-737), root:(2185,223),
    state 0x10, keycode 53 (keysym 0x78, x), same_screen YES,
    XLookupString gives 1 bytes: (78) "x"
    XFilterEvent returns: False

KeyPress event, serial 34, synthetic NO, window 0x400001,
    root 0x246, subw 0x0, time 1764378, (174,-737), root:(2185,223),
    state 0x10, keycode 53 (keysym 0x78, x), same_screen YES,
    XLookupString gives 1 bytes: (78) "x"
    XmbLookupString gives 1 bytes: (78) "x"
    XFilterEvent returns: False

KeyRelease event, serial 34, synthetic NO, window 0x400001,
    root 0x246, subw 0x0, time 1764403, (174,-737), root:(2185,223),
    state 0x10, keycode 53 (keysym 0x78, x), same_screen YES,
    XLookupString gives 1 bytes: (78) "x"
    XFilterEvent returns: False
```

Note that "x" isn't always the key that shows up; it's just the one I triggered in this session.

Any debug tips?

**Comment by jmacey** [comment]
The update doesn't seem to solve my issue. If I run one of my demos that uses the esc key to quit. The next time I run it will just exit on the key esc key seeming to have been pressed. I will do some more investigation but does seem to be related to the above issue.

**Comment by frankli998** [comment]
same issue encountered

**Comment by lucmann** [comment]
same issue on running glxgears/glmark2.

# Environment
```
Windows build number: Microsoft Windows [版本 10.0.21370.1]
Your Distribution version: 20.04
Your WSLg version:  1.0.17+3.Branch.master.Sha.a526dfd5ad03d126bb2d8c528f6c3563e86a40da
```

I paste the weston.log when to run glxgears and glmark2 and the whole log file as an [attachment](https://github.com/microsoft/wslg/files/6445103/weston.log)

```
[11:03:59.558] xfixes selection notify event: owner 2097153
[11:03:59.559] our window, skipping
[11:03:59.559] xfixes selection notify event: owner 2097153
[11:03:59.559] our window, skipping
[11:03:59.559] xfixes selection notify event: owner 2097153
[11:03:59.559] our window, skipping
[11:03:59.559] xfixes selection notify event: owner 2097153
[11:03:59.559] our window, skipping
[11:03:59.559] xfixes selection notify event: owner 2097153
[11:03:59.559] our window, skipping
[11:03:59.621] shell_blend_overlay_icon: app 128x128; overlay 128x128; scale 1.75x1.75
[11:03:59.622] rdp_rail_set_window_icon: original icon width:128 height:128 format:537036936
[11:03:59.623] rdp_rail_set_window_icon: converted icon width:96 height:96 format:537036936
[11:03:59.638] Client: ClientGetAppidReq: WindowId:0x9 does not have appId, or not top level window.
[11:05:00.103] Client: ClientGetAppidReq: WindowId:0xa does not have appId, or not top level window.
[11:05:00.104] shell_blend_overlay_icon: app 128x128; overlay 128x128; scale 1.75x1.75
[11:05:00.104] rdp_rail_set_window_icon: original icon width:128 height:128 format:537036936
[11:05:00.105] rdp_rail_set_window_icon: converted icon width:96 height:96 format:537036936
[11:09:50.921] shell_blend_overlay_icon: app 128x128; overlay 128x128; scale 1.75x1.75
[11:09:50.921] rdp_rail_set_window_icon: original icon width:128 height:128 format:537036936
[11:09:50.921] rdp_rail_set_window_icon: converted icon width:96 height:96 format:537036936
[11:09:50.934] Client: ClientGetAppidReq: WindowId:0xb does not have appId, or not top level window.
```

**Comment by fliespl** [comment]
I have also encounted it in editors. In my case it was "enter" key which created lots of blank lines on start.

**Comment by spronovo** [comment]
Thanks, the problem is now understood. If you happen to change focus away from an X11 application while a key is pressed, Weston doesn't properly tell Xwayland to unpress the key... so Xwayland happily continue repeating the key. Consolidating these report in this issue while we work on a fix for this one.

**Comment by tkyiitd** [comment]
Is this being worked upon?

**Comment by xuanruiqi** [comment]
So this is only for XWayland applications like emacs, right?

**Comment by pcbeard** [comment]
I'm still seeing this bug on W11 [Version 10.0.22000.176], with wslg kernel v5.10.43. I have an SDL2 application just like the one mentioned above, that quits if the user types the escape key OR scans the keyboard using SDL_GetKeyboardState(). If I use `SDL_KEYUP` instead of `SDL_KEYDOWN` the problem goes away.

**Comment by taesoobear** [comment]
I'm also seeing this bug on W11 and the latest wsl. In my case, I am using an FLTK app.   The last key from the last execution of the app is repeated, and passes a complex test like the following (causing immediate exit of the program).
if (event == FL_SHORTCUT && (Fl::event_key()=='q'&&(Fl::event_state()&FL_CTRL)) )

**Comment by GamerSenior** [comment]
Got the same behavior with GLFW and latest WSL version.
After I quit the program pressing a key, it just start with it being pressed.

**Comment by qwcode** [comment]
I see this too.  close apps with ctrl+q, and then open "dolphin" and see "q" character flooding the search bar.   can we get an update? what version is supposed to have fixed this?

**Comment by onomatopellan** [comment]
@qwcode You can get latest WSLg installing the latest WSL Preview https://aka.ms/wslstorepage

**Comment by Shazway** [comment]
Hi, I've recently updated to windows 11 and tried wslG for coding my own graphical projects (which btw is amazing) only small issue, i keyhook the escape key to exit my games quicker and close the window, long story short, first time i launch my "games" that i coded it would be fine no problem, but second and every other times, the escape button is "pressed" immediately after launch, i have checked by using somewhat of a display of the keycode that is enetered and it "conveys" that as soon as i launch either of the games that hook keys, the escape button is pressed, by disabling my "close game" function i can see it is "spammed" multiple times in input obviously nothing is wrong with either my code or my keyboard, i have double checked on a linux device and it works perfectly fine. (i also did upgrade my wsl to the latest version to no avail)
My repositories are public if needed to be tested, (names are so_long and cub3D, works on linux only, and i could always sharescreen the issue in a video call if needed ? Idk how this works but i guess i wanted to post a little message still).

**Comment by NotTheDr01ds** [comment]
@Shazway

> i also did upgrade my wsl to the latest version to no avai

Did you update to the *Preview*, though?  That's not clear from your question.  If `wsl --status` doesn't show `WSL version: 0.66.2.0`, then you probably are still running the non-Preview version, where the bug hasn't been fixed.  If that's the case, then see the post just above yours for how to do that.

**Comment by Shazway** [comment]
I am now downloading the WSL preview on microsoft store, will it update my wsl or do i have to set it up again?
It's also my bad for not noticing the message you mentionned above, i'm a bit new to this my apologies.. I'll edit this message after testing my issue out again after the download, thank you for your time.

**Comment by NotTheDr01ds** [comment]
@Shazway

> i'm a bit new to this my apologies

No worries.  We're all new to it at some point, of course ;-).

Good to hear it's working for you!

Side-note -- I'd recommend editing your comment above to reduce the font size (you probably have the text as a heading in Markdown or something?).  It comes across a bit ... loud ;-)

**Comment by Shazway** [comment]
Thanks ! However, i have no idea why the text turned out like that T_T i'll try changing it just now

**Comment by lucmann** [comment]
@NotTheDr01ds, 

> If wsl --status doesn't show WSL version: 0.66.2.0, then you probably are still running the non-Preview version, where the bug hasn't been fixed.

it indeed works on new WSL version, but `wsl --status` doesn't show anything about WSL version, while `wsl --version` does on my machine.

```
>wsl --status
默认分发: Ubuntu-20.04
默认版本: 2
```

```
>wsl --version
WSL 版本： 0.67.6.0
内核版本： 5.15.62.1
WSLg 版本： 1.0.44
MSRDC 版本： 1.2.3401
Direct3D 版本： 1.606.4
DXCore 版本： 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows版本： 10.0.22621.601
```

**Comment by ahdyt** [comment]
Upvote! got spammed c chars when opening emacs.

**Comment by NotTheDr01ds** [comment]
@ahdyt I'm not seeing an upvote on any particular comment, but I might have missed it.  Just wanted to make sure you saw that this is fixed, right?

**Comment by ahdyt** [comment]
> @ahdyt I'm not seeing an upvote on any particular comment, but I might have missed it. Just wanted to make sure you saw that this is fixed, right?

Mine not,

`wsl --status`

```
Default Distribution: docker-desktop
Default Version: 2

Windows Subsystem for Linux was last updated on 8/8/2022
The Windows Subsystem for Linux kernel can be manually updated with 'wsl --update', but automatic updates cannot occur due to your system settings.
To receive automatic kernel updates, please enable the Windows Update setting: 'Receive updates for other Microsoft products when you update Windows'.
For more information please visit https://aka.ms/wsl2kernel.

Kernel version: 5.10.102.1
```

`wsl --version` no flag --version, so it shows help 

Previously i have to use xming or another xserver to make wsl gui available to windows, but I think the perfs not good enough and audio video doesn't work, so I decided to delete all of them, but updating my windows to latest version get me to this wslg, so it's automatically enables gui/wm behavior which is good, but well, it's related to closed issue(https://github.com/microsoft/wslg/issues/215), when you exit emacs(C-x C-c) then when you open emacs again, it wil type cccccccccccccccccc until u click anything in keyboard to stop it.

I install distro using `wsl --install or wsl --import` not from the store.

If it's fixed perhaps this issue also closed?

**Comment by NotTheDr01ds** [comment]
@lucmann Ah, sorry - Missed this earlier.  Yes, 0.67.6 changed `wsl --status` to not report version numbers any longer.  When I wrote it, you had to use `wsl --status`; now (as you noticed), you have to use `wsl --version`.

It confused the heck out of me when I couldn't get `wsl --status` to work on 0.67.6 -- I thought I had installation issues.

I'll edit the info above so that's it more clear.  Thanks for pointing it out!

**Comment by NotTheDr01ds** [comment]
@ahdyt You must install from the Store (or manually download and install from the [Releases](https://github.com/microsoft/WSL/releases) page) to update to the latest version.  Until then, you are on the Windows 11 22000 release from last October.

> If it's fixed perhaps this issue also closed?

As I said a few comments above:

> A bit surprised to run across this issue (in my search for another issue) and find it not "Closed", or at least something like "Fixed Pending".

I'm sure this is just a case of the WSLg team not having triaged this particular issue recently.  That happens quite a bit, unfortunately, especially on larger projects.  Every so often, hopefully, someone will need to make a conscious effort to close out old issues.

It's almost certainly fixed, though, as you can see by reading the comments above from people who have installed the Preview WSL release and no longer have the problem.

**Comment by NotTheDr01ds** [comment]
@spronovo When you get a chance, can you validate that this is fixed and close it out?  Multiple people have confirmed that it is no longer an issue in recent Preview releases.  Thanks!

**Comment by ahdyt** [comment]
@NotTheDr01ds Oh yeah, I download from the Releases page and it's worked like a charm. I thought I have to be an insider program according to here(https://learn.microsoft.com/en-us/windows/wsl/install), but because it's open sourced it's now accessible without doing so.

**Comment by NotTheDr01ds** [comment]
@ahdyt Oh, and just for clarity, it's actually not open-sourced.  Only the binaries can be downloaded from that Github repo.

**Comment by ahdyt** [comment]
> @ahdyt Oh, and just for clarity, it's actually not open-sourced. Only the binaries can be downloaded from that Github repo.

Thanks for correcting me.
